import type { Template } from '../types/template.types';

export const mockTemplates: Template[] = [
  {
    id: 'tpl-1',
    name: 'Promo Black Friday',
    description: 'Template pour les promotions de Black Friday avec countdown timer',
    category: 'seasonal',
    thumbnail: 'https://picsum.photos/seed/bf1/400/300',
    status: 'active',
    structure: {
      basicInfo: {
        objective: 'conversions',
        channels: ['facebook', 'instagram', 'email'],
        type: 'promotion',
      },
      creatives: {
        headline: '🔥 Black Friday : -50% sur tout le site !',
        caption: 'Profitez de nos offres exceptionnelles pendant 48h seulement.',
        callToAction: 'Profiter maintenant',
      },
      planning: {
        budget: 5000,
      },
    },
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-15'),
    createdBy: 'user-1',
    stats: {
      usageCount: 45,
      lastUsedAt: new Date('2024-10-14'),
      averageCTR: 4.2,
      averageConversion: 2.8,
      successRate: 85,
    },
    tags: ['promotion', 'seasonal', 'high-performance'],
    isFavorite: true,
    isShared: true,
    channels: ['facebook', 'instagram', 'email'],
  },
  {
    id: 'tpl-2',
    name: 'Newsletter Mensuelle',
    description: 'Template standard pour newsletter mensuelle avec sections produits',
    category: 'newsletter',
    thumbnail: 'https://picsum.photos/seed/nl1/400/300',
    status: 'active',
    structure: {
      basicInfo: {
        objective: 'engagement',
        channels: ['email'],
        type: 'newsletter',
      },
      creatives: {
        headline: 'Découvrez nos nouveautés du mois',
        caption: 'Restez informé de nos dernières actualités et offres exclusives.',
        callToAction: 'Lire la suite',
      },
    },
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2024-10-10'),
    createdBy: 'user-1',
    stats: {
      usageCount: 32,
      lastUsedAt: new Date('2024-10-05'),
      averageCTR: 3.5,
      successRate: 78,
    },
    tags: ['newsletter', 'recurring'],
    isFavorite: false,
    isShared: true,
    channels: ['email'],
  },
  {
    id: 'tpl-3',
    name: 'Génération de Leads - Ebook',
    description: 'Template pour campagne de génération de leads via ebook gratuit',
    category: 'lead_generation',
    thumbnail: 'https://picsum.photos/seed/lead1/400/300',
    status: 'active',
    structure: {
      basicInfo: {
        objective: 'leads',
        channels: ['facebook', 'linkedin', 'google_ads'],
        type: 'lead_generation',
      },
      creatives: {
        headline: 'Guide gratuit : 10 stratégies marketing qui fonctionnent',
        caption: "Téléchargez notre ebook exclusif et boostez vos ventes dès aujourd'hui.",
        callToAction: 'Télécharger gratuitement',
      },
      planning: {
        budget: 3000,
      },
    },
    createdAt: new Date('2024-08-20'),
    updatedAt: new Date('2024-10-12'),
    createdBy: 'user-2',
    stats: {
      usageCount: 28,
      lastUsedAt: new Date('2024-10-11'),
      averageCTR: 5.1,
      averageConversion: 12.5,
      successRate: 92,
    },
    tags: ['lead-gen', 'ebook', 'b2b'],
    isFavorite: true,
    isShared: false,
    channels: ['facebook', 'linkedin', 'google'],
  },
  {
    id: 'tpl-4',
    name: 'Lancement Produit - Teaser',
    description: "Template teaser pour créer l'anticipation avant un lancement produit",
    category: 'product_launch',
    thumbnail: 'https://picsum.photos/seed/prod1/400/300',
    status: 'active',
    structure: {
      basicInfo: {
        objective: 'awareness',
        channels: ['instagram', 'tiktok', 'facebook'],
        type: 'product_launch',
      },
      creatives: {
        headline: "🚀 Quelque chose d'incroyable arrive...",
        caption: 'Restez connectés pour découvrir notre nouvelle innovation le 15 novembre.',
        callToAction: 'En savoir plus',
      },
    },
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-10-08'),
    createdBy: 'user-3',
    stats: {
      usageCount: 15,
      lastUsedAt: new Date('2024-10-07'),
      averageCTR: 6.8,
      successRate: 88,
    },
    tags: ['product-launch', 'teaser', 'viral'],
    isFavorite: false,
    isShared: true,
    channels: ['instagram', 'tiktok', 'facebook'],
  },
  {
    id: 'tpl-5',
    name: 'Webinar Registration',
    description: 'Template pour inscription à un webinar avec rappels automatiques',
    category: 'event',
    thumbnail: 'https://picsum.photos/seed/web1/400/300',
    status: 'active',
    structure: {
      basicInfo: {
        objective: 'leads',
        channels: ['email', 'linkedin'],
        type: 'event',
      },
      creatives: {
        headline: 'Webinar gratuit : Les tendances marketing 2025',
        caption: 'Rejoignez-nous le 20 novembre pour un webinar exclusif avec nos experts.',
        callToAction: 'Réserver ma place',
      },
    },
    createdAt: new Date('2024-09-10'),
    updatedAt: new Date('2024-10-13'),
    createdBy: 'user-2',
    stats: {
      usageCount: 22,
      lastUsedAt: new Date('2024-10-12'),
      averageCTR: 4.5,
      averageConversion: 8.2,
      successRate: 81,
    },
    tags: ['webinar', 'event', 'b2b'],
    isFavorite: true,
    isShared: true,
    channels: ['email', 'linkedin'],
  },
  {
    id: 'tpl-6',
    name: 'Réengagement Client',
    description: 'Template pour réactiver les clients inactifs avec offre spéciale',
    category: 'retention',
    thumbnail: 'https://picsum.photos/seed/ret1/400/300',
    status: 'active',
    structure: {
      basicInfo: {
        objective: 'conversions',
        channels: ['email', 'sms'],
        type: 'retention',
      },
      creatives: {
        headline: 'Vous nous manquez ! Voici 20% de réduction',
        caption:
          "Cela fait un moment... Revenez et profitez d'une remise exclusive rien que pour vous.",
        callToAction: 'Utiliser ma réduction',
      },
    },
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2024-10-09'),
    createdBy: 'user-1',
    stats: {
      usageCount: 38,
      lastUsedAt: new Date('2024-10-08'),
      averageCTR: 3.8,
      averageConversion: 6.5,
      successRate: 75,
    },
    tags: ['retention', 'winback', 'discount'],
    isFavorite: false,
    isShared: true,
    channels: ['email', 'sms'],
  },
  {
    id: 'tpl-7',
    name: 'Social Media Contest',
    description: 'Template pour organiser un concours sur les réseaux sociaux',
    category: 'promotion',
    thumbnail: 'https://picsum.photos/seed/contest1/400/300',
    status: 'draft',
    structure: {
      basicInfo: {
        objective: 'engagement',
        channels: ['instagram', 'facebook', 'tiktok'],
        type: 'promotion',
      },
      creatives: {
        headline: '🎁 Grand Concours : Gagnez un an de produits gratuits !',
        caption: 'Participez en 3 clics et tentez de remporter notre grand prix.',
        callToAction: 'Participer maintenant',
      },
    },
    createdAt: new Date('2024-10-05'),
    updatedAt: new Date('2024-10-14'),
    createdBy: 'user-3',
    stats: {
      usageCount: 0,
    },
    tags: ['contest', 'engagement', 'viral'],
    isFavorite: false,
    isShared: false,
    channels: ['instagram', 'facebook', 'tiktok'],
  },
  {
    id: 'tpl-8',
    name: 'Flash Sale 24h',
    description: 'Template pour vente flash avec urgence et timer',
    category: 'promotion',
    thumbnail: 'https://picsum.photos/seed/flash1/400/300',
    status: 'active',
    structure: {
      basicInfo: {
        objective: 'conversions',
        channels: ['facebook', 'instagram', 'email'],
        type: 'promotion',
      },
      creatives: {
        headline: "⚡ Vente Flash 24h : Jusqu'à -70% !",
        caption: "Dépêchez-vous, l'offre expire dans 24h. Stock limité !",
        callToAction: "J'en profite",
      },
      planning: {
        budget: 2500,
      },
    },
    createdAt: new Date('2024-09-20'),
    updatedAt: new Date('2024-10-11'),
    createdBy: 'user-1',
    stats: {
      usageCount: 52,
      lastUsedAt: new Date('2024-10-10'),
      averageCTR: 7.2,
      averageConversion: 4.1,
      successRate: 90,
    },
    tags: ['flash-sale', 'urgency', 'high-conversion'],
    isFavorite: true,
    isShared: true,
    channels: ['facebook', 'instagram', 'email'],
  },
];
